### ISSUE TITLE
CI build failing

### ISSUE THREAD

**Issue by andrew-saydjari** [conda-forge/crowdsourcephoto-feedstock#1]
The CI build of the package failed even though the checks passed on linux and macOS on the staged recipes PR. The offending line is:

tensorflow 2.4.3 has requirement wrapt~=1.12.1, but you have wrapt 1.13.2

It is unclear to me why an error in version requirements would occur at this stage? Is there any advice for how I should go about fixing? @conda-forge/help-python

**Comment by dopplershift** [comment]
Looks like it started failing here because for some reason here `tensorflow=2.4.3` was installed in the environment, while on staged-recipes it was `tensorflow=2.6.0`.

This matters because the tensorflow 2.4 packages have a slightly incorrect specification for the `wrapt` dependency. Removing `pip check` would work around it, but I'm leaning towards fixing the `tensorflow` metadata.

**Comment by andrew-saydjari** [comment]
Ok. I will make a PR on this repo where I change `tensorflow >=2` to `tensorflow >=2.5` to avoid the problems with 2.4.
